[package]
name = "SlopExplore"
version = "0.2.1"
edition = "2021"

[target.'cfg(windows)'.dependencies]
window-vibrancy = "0.6"
winreg = "0.55"

[dependencies]
eframe = "0.31.1"
egui_extras = { version = "0.31.1", features = ["svg"] }
dirs = "6.0"
dunce = "1.0"
open = "5.3"
rfd = "0.15"
sysinfo = "0.35"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
image = { version = "0.25", features = ["ico"] }
trash = "5.2.9"
chrono = "0.4"
notify = "8"
raw-window-handle = "0.6"

[build-dependencies]
winres = "0.1"

[package.metadata.appimage]
icon = "assets/logo.png"
desktop_entry = "other/SlopExplore.desktop"
